# ============================================================
#  Perfil LOCAL — Sobreescribe valores para desarrollo local
#  Este archivo NO debe commitearse con credenciales reales
# ============================================================

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/franchise_db
    username: franchise_user
    password: franchise_pass

  flyway:
    url: jdbc:mysql://localhost:3306/franchise_db
    user: franchise_user
    password: franchise_pass

logging:
  level:
    com.accenture.franchise: DEBUG
    io.r2dbc.mysql: TRACE